AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestContainerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: test-container
      ImageUri: hello-container

      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
